on: [push]

jobs:
  post_lessons_job:
    runs-on: ubuntu-latest
    name: A job to post current lessons to hosts
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build web
    - run: flutter pub run pdfx:install_web
